# Project Information
site_name: VATPAC Standard Operating Procedures
site_url: https://sops.vatpac.org
repo_url: https://github.com/vatpac-technology/sops
repo_name: vatpac-technology/sops
edit_uri: "" #removes edit button and icon
copyright: ""

# Configuration
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/mini-logo.png
  font:
    text: Maven Pro
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
  favicon: assets/images/mini-logo.png
  icon:
    repo: fontawesome/brands/github

# Plugins
plugins:
  - search:
      lang: en
  - glightbox    
  - awesome-pages
  - git-revision-date-localized:
      type: date
  - redirects:
      redirect_maps:
        'aerodromes/Adelaide.md': 'aerodromes/classc/Adelaide.md'
        'aerodromes/Amberley.md': 'aerodromes/classc/Amberley.md'
        'aerodromes/Brisbane.md': 'aerodromes/classc/Brisbane.md'
        'aerodromes/Cairns.md': 'aerodromes/classc/Cairns.md'
        'aerodromes/Canberra.md': 'aerodromes/classc/Canberra.md'
        'aerodromes/Curtin.md': 'aerodromes/classc/Curtin.md'
        'aerodromes/Darwin.md': 'aerodromes/classc/Darwin.md'
        'aerodromes/EastSale.md': 'aerodromes/classc/EastSale.md'
        'aerodromes/Edinburgh.md': 'aerodromes/classc/Edinburgh.md'
        'aerodromes/Essendon.md': 'aerodromes/classc/Essendon.md'
        'aerodromes/Gingin.md': 'aerodromes/classc/Gingin.md'
        'aerodromes/Goldy.md': 'aerodromes/classc/Goldy.md'
        'aerodromes/Learmonth.md': 'aerodromes/classc/Learmonth.md'
        'aerodromes/Melbourne.md': 'aerodromes/classc/Melbourne.md'
        'aerodromes/Nowra.md': 'aerodromes/classc/Nowra.md'
        'aerodromes/Oakey.md': 'aerodromes/classc/Oakey.md'
        'aerodromes/Pearce.md': 'aerodromes/classc/Pearce.md'
        'aerodromes/Perth.md': 'aerodromes/classc/Perth.md'
        'aerodromes/Richmond.md': 'aerodromes/classc/Richmond.md'
        'aerodromes/Scherger.md': 'aerodromes/classc/Scherger.md'
        'aerodromes/Sydney.md': 'aerodromes/classc/Sydney.md'
        'aerodromes/Tindal.md': 'aerodromes/classc/Tindal.md'
        'aerodromes/Townsville.md': 'aerodromes/classc/Townsville.md'
        'aerodromes/Williamtown.md': 'aerodromes/classc/Williamtown.md'
        'aerodromes/Archerfield.md': 'aerodromes/classd/Archerfield.md'
        'aerodromes/Avalon.md': 'aerodromes/classd/Avalon.md'
        'aerodromes/Bankstown.md': 'aerodromes/classd/Bankstown.md'
        'aerodromes/Camden.md': 'aerodromes/classd/Camden.md'
        'aerodromes/Hobart.md': 'aerodromes/classd/Hobart.md'
        'aerodromes/Jandakot.md': 'aerodromes/classd/Jandakot.md'
        'aerodromes/Launceston.md': 'aerodromes/classd/Launceston.md'
        'aerodromes/Mackay.md': 'aerodromes/classd/Mackay.md'
        'aerodromes/Moorabbin.md': 'aerodromes/classd/Moorabbin.md'
        'aerodromes/Parafield.md': 'aerodromes/classd/Parafield.md'
        'aerodromes/Rockhampton.md': 'aerodromes/classd/Rockhampton.md'
        'aerodromes/Albury.md': 'aerodromes/procedural/Albury.md'
        'aerodromes/Alice.md': 'aerodromes/procedural/Alice.md'
        'aerodromes/Broome.md': 'aerodromes/procedural/Broome.md'
        'aerodromes/Coffs.md': 'aerodromes/procedural/Coffs.md'
        'aerodromes/Hammo.md': 'aerodromes/procedural/Hammo.md'
        'aerodromes/Karratha.md': 'aerodromes/procedural/Karratha.md'
        'aerodromes/Sunshinecoast.md': 'aerodromes/procedural/Sunshinecoast.md'
        'aerodromes/Tamworth.md': 'aerodromes/procedural/Tamworth.md'
        'aerodromes/Woomera.md': 'aerodromes/procedural/Woomera.md'
        'controller-skills/annotations.md': 'client/annotations.md'
        'controller-skills/cpdlc.md': 'client/cpdlc.md'
        'controller-skills/maestro.md': 'client/maestro.md'
        'controller-skills/vatsys.md': 'client/vatsys.md'

# Styling Front-end
extra_css:
  - stylesheets/extra.css
  - stylesheets/admonitions.css
  - stylesheets/navigation.css
  - stylesheets/custom-toc.css

# Extra Functions / Customizations
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vatpac-technology
      name: VATPAC on Github
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/vatpac
      name: VATPAC on Facebook
    - icon: fontawesome/brands/discord
      link: https://discord.vatpac.org
      name: VATPAC on Discord

# Additional Markdown Extensions to use bundled icon sets
markdown_extensions:
  - toc:
      toc_class: custom-toc
  - meta # Add front matter to a document
  - admonition # Makes things pretty
  - pymdownx.superfences # Nestled code
  - attr_list # Add HTML attributes and CSS classes to Markdown elements
  - pymdownx.tabbed: # Content tabs
      alternate_style: true
  - pymdownx.details # Additional features to admonition
  - pymdownx.caret # Formatting Extension
  - pymdownx.critic # Alternate Formatting Extension
  - pymdownx.mark # Formatting Extension
  - pymdownx.tilde # Formatting Extension
  - pymdownx.keys # Visual keyboard keys extension
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji: # Allows emoji style inline embeds for icons
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html #enables the use of image figures
  - abbr
  - pymdownx.snippets
  - pymdownx.arithmatex: # Allows the use of math formulas with proper formatting
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

validation:
  unrecognized_links: ignore